# Generated by Django 3.2.7 on 2022-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_files_create_post_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
