# Generated by Django 3.2.7 on 2022-05-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_post',
            name='description',
        ),
    ]
