# Generated by Django 3.2.7 on 2022-05-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_create_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerd_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('rePass', models.CharField(max_length=25)),
            ],
        ),
    ]
