# Generated by Django 3.2.7 on 2022-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_create_post_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_post',
            name='feelings',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='create_post',
            name='places',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
