# Generated by Django 3.2.7 on 2022-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220523_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='author_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
