# Generated by Django 3.2.7 on 2022-06-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stories_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
