# Generated by Django 3.2.7 on 2022-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_comment_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_section',
            name='comment_author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
